spring:
  # redis
  redis:
    host: 49.234.39.72
    port: 6378
    password:
    timeout: 30000
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
  shardingsphere:
    datasource:
      # 写数据源master
      master:
        url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      # 读数据源slave0
      slave0:
        url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      # 读数据源slave1
      slave1:
        url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456